assign:
  'Team Business': [ 'daheeParkk', 'ImTotem', 'DHkimgit' ]
  'Team Campus': [ 'krSeonghyeon', 'Soundbar91', 'dradnats1012', 'duehee' ]
  'Team User': [ 'Choon0414', 'Baejinho4028', 'kih1015' ]
