Team Business:
  prs:
    reviewers:
      - daheeParkk
      - ImTotem
      - DHkimgit

Team Campus:
  prs:
    reviewers:
      - krSeonghyeon
      - Soundbar91
      - dradnats1012
      - duehee

Team User:
  prs:
    reviewers:
      - Choon0414
      - Baejinho4028
      - kih1015
