ALTER TABLE device
DROP FOREIGN KEY FK_DEVICE_ON_USER_ID;

ALTER TABLE device
    ADD CONSTRAINT FK_DEVICE_ON_USER_ID
        FOREIGN KEY (user_id)
            REFERENCES users(id) ON DELETE CASCADE;
