jwt:
  secret-key: test-secret-key
  access-token:
    expiration-time: 600000

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      port: 8888
      host: localhost

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
