jwt:
  secret-key: EXAMPLE7A3E4F37B3DAD9CD8KEY6AA4B1AF7123!@#
  access-token:
    expiration-time: 600000 # (ms) = 10 minutes

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: "classpath:/mail/"
    suffix: ".html"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

swagger:
  server-url: http://localhost:8080

slack:
  notify_koin_event_url:

aws:
  ses:
    access-key:
    secret-key:
