CREATE TABLE `koin`.`members` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `student_number` VARCHAR(20) NULL DEFAULT NULL,
  `track_id` INT(10) UNSIGNED NOT NULL,
  `position` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL,
  `image_url` TEXT NULL DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;