CREATE TABLE `koin`.`shop_owners` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE `user_email_idx`(`user_id`, `shop_id`),
  CONSTRAINT `shop_owners_fk_shop_id` FOREIGN KEY(`shop_id`) REFERENCES `koin`.`shops`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `shop_owners_fk_user_id` FOREIGN KEY(`user_id`) REFERENCES `koin`.`users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;