name: KOIN_API_V2 CI Config

on:
  push:
    paths: '/**'
  pull_request:
    branches:
      - develop
      - main

permissions:
  pull-requests: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Run gradle build
        run: ./gradlew build

      - name: comments test result on PR
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: comments test result in failed line if test failed
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.PAT }}
