name: KOIN_API_V2 CI Config

on:
  push:
    paths: '/**'
  pull_request:
    branches:
      - develop
      - main

permissions:
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew build --build-cache

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Annotate failed tests
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.PAT }}

