name: "PR Automation"

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  # 이슈에 따라 라벨 추가
  sync-labels:
    name: Issue Labeler
    needs: pr-labeler
    runs-on: ubuntu-latest
    steps:
      - uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  # 브랜치 접두사에 따라 라벨 추가
  pr-labeler:
    name: Branch Prefix Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 팀라벨에 맞는 리뷰어 할당
  assign:
    name: Assign Reviewers by Label
    needs: sync-labels
    if: github.event_name == 'pull_request' && contains(toJson(github.event.pull_request.labels), 'Team')
    runs-on: ubuntu-latest
    steps:
      - name: Assign Team Business
        if: contains(toJson(github.event.pull_request.labels), 'Team Business')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_business.yml

      - name: Assign Team Campus
        if: contains(toJson(github.event.pull_request.labels), 'Team Campus')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_campus.yml

      - name: Assign Team User
        if: contains(toJson(github.event.pull_request.labels), 'Team User')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_user.yml
