name: "Assign Reviewers by Label"
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assign reviewers based on label
        uses: totallymoney/assign-reviewers-by-labels-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
