name: "Assign Reviewers by Label"
on:
  pull_request:
    types: [labeled, unlabeled]
  workflow_run:
    workflows: ["PR Labeler"]
    types: [completed]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Team Business
        if: contains(toJson(github.event.pull_request.labels), 'Team Business')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_business.yml

      - name: Check if Team Campus
        if: contains(toJson(github.event.pull_request.labels), 'Team Campus')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_campus.yml

      - name: Check if Team User
        if: contains(toJson(github.event.pull_request.labels), 'Team User')
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign_team_user.yml
